### ISSUE TITLE
Is this branch deletable?

### ISSUE THREAD

**Issue by ayjayt** [ayjayt/ayjayt.github.io#6]
I approved three PRs but I saw you only merged one (or maybe two?) One was closed. Is that because the changes were redundant? Is this branch deletable: https://github.com/ayjayt/ayjayt.github.io/tree/normalization_example

**Comment by ayjayt** [comment]
@shpew12 for visibility

**Comment by oliverchubet** [comment]
Yeah, it was redundant.

**Comment by ayjayt** [comment]
Awesome, issue closed.
